version: '3'

services:
  frontend:
    build:
      context: ./calculator-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./calculator-backend
    ports:
      - "5000:5000"
